nome= str (input('Digite seu nome completo :'))
print('Seu nome em maiusculo é', nome.upper())
print('Seu nome em minusculo é',nome.lower())
print('Seu nome tem {} letras'.format (len(nome) - nome.count(' ')))
print('Seu primeiro nome tem {} letras'.format(nome.find(' ')))
